### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by ni-ko-b** [cff29546/pzmap2dzi#28]
```C:\Program Files (x86)\Steam\steamapps\common\ProjectZomboid/media/texturepacks\ApCom.pack: version 0, 1 pages
C:\Program Files (x86)\Steam\steamapps\common\ProjectZomboid/media/texturepacks\ApComUI.pack: version 0, 1 pages
C:\Program Files (x86)\Steam\steamapps\common\ProjectZomboid/media/texturepacks\Erosion.pack: version 0, 5 pages
C:\Program Files (x86)\Steam\steamapps\common\ProjectZomboid/media/texturepacks\JumboTrees2x.pack: version 0, 12 pages
C:\Program Files (x86)\Steam\steamapps\common\ProjectZomboid/media/texturepacks\RadioIcons.pack: version 0, 1 pages
C:\Program Files (x86)\Steam\steamapps\common\ProjectZomboid/media/texturepacks\Tiles2x.floor.pack: version 1, 5 pages
C:\Program Files (x86)\Steam\steamapps\common\ProjectZomboid/media/texturepacks\Tiles2x.pack: version 1, 224 pages
job: 25386/25386 worker: 0/16
render [base] for map [default]
Preparing data
Planning tasks
Working
job:[(22, 398, 396, None)] error, Exception: unpack requires a buffer of 4 bytes
job:[(22, 981, 633, None)] error, Exception: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
job:[(22, 1981, 512, None)] error, Exception: 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte
job:[(22, 481, 647, None)] error, Exception: unpack requires a buffer of 4 bytes
job:[(22, 1496, 364, None)] error, Exception: unpack requires a buffer of 4 bytes
job:[(22, 807, 216, None)] error, Exception: unpack requires a buffer of 4 bytes
job:[(22, 1539, 1015, None)] error, Exception: unpack requires a buffer of 4 bytes
job:[(22, 1157, 840, None)] error, Exception: unpack requires a buffer of 4 bytes
job:[(22, 1421, 965, None)] error, Exception: unpack requires a buffer of 4 bytes
job:[(22, 798, 308, None)] error, Exception: unpack requires a buffer of 4 bytes
job:[(22, 1237, 765, None)] error, Exception: unpack requires a buffer of 4 bytes
job:[(22, 2267, 603, None)] error, Exception: unpack requires a buffer of 4 bytes
job:[(22, 1583, 1032, None)] error, Exception: unpack requires a buffer of 4 bytes
Traceback (most recent call last):
Traceback (most recent call last):
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
Traceback (most recent call last):
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 82, in load_lotheader
    room, pos = read_room(data, pos)
                ^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 20, in read_room
    x, pos = util.read_int32(data, pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 71, in load_lotheader
    tile_names.append(name.decode('utf8'))
                      ^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\util.py", line 32, in read_int32
    return struct.unpack('i', data[pos: pos+4])[0], pos + 4
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
Traceback (most recent call last):: 0.00 MB
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
Traceback (most recent call last):
Traceback (most recent call last):
struct.error: unpack requires a buffer of 4 bytes
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
Traceback (most recent call last):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
Traceback (most recent call last):
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
Traceback (most recent call last):
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
worker[0] error[unpack requires a buffer of 4 bytes]
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 82, in load_lotheader
    room, pos = read_room(data, pos)
                ^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 82, in load_lotheader
    room, pos = read_room(data, pos)
                ^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 22, in read_room
    w, pos = util.read_int32(data, pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 21, in read_room
    y, pos = util.read_int32(data, pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 71, in load_lotheader
    tile_names.append(name.decode('utf8'))
                      ^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 82, in load_lotheader
    room, pos = read_room(data, pos)
                ^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\util.py", line 32, in read_int32
    return struct.unpack('i', data[pos: pos+4])[0], pos + 4
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\util.py", line 32, in read_int32
    return struct.unpack('i', data[pos: pos+4])[0], pos + 4
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 82, in load_lotheader
    room, pos = read_room(data, pos)
                ^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 82, in load_lotheader
    room, pos = read_room(data, pos)
                ^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 23, in read_room
    h, pos = util.read_int32(data, pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 82, in load_lotheader
    room, pos = read_room(data, pos)
                ^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 23, in read_room
    h, pos = util.read_int32(data, pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 82, in load_lotheader
    room, pos = read_room(data, pos)
                ^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 23, in read_room
    h, pos = util.read_int32(data, pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 82, in load_lotheader
    room, pos = read_room(data, pos)
                ^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\util.py", line 32, in read_int32
    return struct.unpack('i', data[pos: pos+4])[0], pos + 4
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 82, in load_lotheader
    room, pos = read_room(data, pos)
                ^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 23, in read_room
    h, pos = util.read_int32(data, pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 82, in load_lotheader
    room, pos = read_room(data, pos)
                ^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\util.py", line 32, in read_int32
    return struct.unpack('i', data[pos: pos+4])[0], pos + 4
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 22, in read_room
    w, pos = util.read_int32(data, pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\util.py", line 32, in read_int32
    return struct.unpack('i', data[pos: pos+4])[0], pos + 4
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 20, in read_room
    x, pos = util.read_int32(data, pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 22, in read_room
    w, pos = util.read_int32(data, pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\util.py", line 32, in read_int32
    return struct.unpack('i', data[pos: pos+4])[0], pos + 4
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 22, in read_room
    w, pos = util.read_int32(data, pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\util.py", line 32, in read_int32
    return struct.unpack('i', data[pos: pos+4])[0], pos + 4
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\util.py", line 32, in read_int32
    return struct.unpack('i', data[pos: pos+4])[0], pos + 4
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
struct.error: unpack requires a buffer of 4 bytes
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\util.py", line 32, in read_int32
    return struct.unpack('i', data[pos: pos+4])[0], pos + 4
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\util.py", line 32, in read_int32
    return struct.unpack('i', data[pos: pos+4])[0], pos + 4
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
struct.error: unpack requires a buffer of 4 bytes
job:[(22, 1903, 408, None)] error, Exception: unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\mptask.py", line 53, in _run
    result = self.worker.on_job(arg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\scheduling.py", line 297, in on_job
    self.dzi.render_tile(ic, self.render, x, y, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\pzdzi.py", line 386, in render_tile
    render.square(im_getter, ox, oy, sx, sy, layer)
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 34, in square
    data = load_cell_cached(self.input, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\render_impl\base.py", line 12, in load_cell_cached
    return cell.load_cell(path, cx, cy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\cell.py", line 65, in load_cell
    header = lotheader.load_lotheader(lotheader_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 82, in load_lotheader
    room, pos = read_room(data, pos)
                ^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\lotheader.py", line 21, in read_room
    y, pos = util.read_int32(data, pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pzmap\pzmap2dzi\pzmap2dzi\util.py", line 32, in read_int32
    return struct.unpack('i', data[pos: pos+4])[0], pos + 4
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
job: 3/1951569 worker: 0/16 cache: 0.00 MB
time used 0:00:08.690829
cache max used: 0.00 MB
Render interrupted: error
All done```

**Comment by cff29546** [comment]
If you are palying b42 UNSTABLE version of the game, please try the [experiment branch](https://github.com/cff29546/pzmap2dzi/tree/b42) for b42.
